import type { Car } from "@/types/car";

export const cars: Car[] = [
  {
    id: "toyota-yaris",
    category: "Hatchback",
    name: "Toyota Yaris",
    image: "/yaris.webp",
    transmission: "Automatic/Manual",
    seats: 3,
    bags: 1,
    rating: 4.7,
    price: 70,
  },
  {
    id: "alphard",
    category: "Minivan",
    name: "Alphard",
    image: "/alphard.webp",
    transmission: "Automatic",
    seats: 5,
    bags: 2,
    rating: 4.8,
    price: 95,
  },
  {
    id: "lexus-nx300",
    category: "SUV",
    name: "Lexus NX - 300",
    image: "/lexus.webp",
    transmission: "Automatic",
    seats: 3,
    bags: 2,
    rating: 4.7,
    price: 88,
  },
  {
    id: "camry",
    category: "Sedan",
    name: "Camry",
    image: "/camry.webp",
    transmission: "Automatic",
    seats: 3,
    bags: 2,
    rating: 4.9,
    price: 50,
  },
];
